### ISSUE TITLE
LocalizationService seem not working at all

### ISSUE THREAD

**Issue by Stupidman22** [akexorcist/Localization#104]
Hello bro, Thanks for creating this useful library. But right now I'm having a problem
I have an service extend LocalizationService
when creating it, i had tried to add some custom view . When change other language. My custom view did not update language. 
It use the default language of device. I using samsung device with os version 11

**Comment by akexorcist** [comment]
Do you add CustomView in Service? How?

**Comment by akexorcist** [comment]
Since AndroidX AppCompat has per-app language preferences for backward compatibility. Please migrate this library to AndroidX for more stability, compatibility, and longer support from Google team.

See [Migrate to AndroidX guide](https://github.com/akexorcist/Localization/blob/master/MIGRATE_TO_ANDROIDX.md)

Thank you for your support
