### ISSUE TITLE
it is make hyper pay it online payment get way stop !

### ISSUE THREAD

**Issue by magdy0000** [akexorcist/Localization#115]

**Comment by akexorcist** [comment]
Could you provide more information about issue?

**Comment by akexorcist** [comment]
Since AndroidX AppCompat has per-app language preferences for backward compatibility. Please migrate this library to AndroidX for more stability, compatibility, and longer support from Google team.

See [Migrate to AndroidX guide](https://github.com/akexorcist/Localization/blob/master/MIGRATE_TO_ANDROIDX.md)

Thank you for your support
