### ISSUE TITLE
Compatability with Android Hilt

### ISSUE THREAD

**Issue by sevenreup** [akexorcist/Localization#63]
My application started crashing after I started using Hilt for dependency injection every time I change the language. I think the problem is coming when the application tries to recreate the activity.
I dont know if this is a problem on my side or maybe the library doesn't have dependency injection support.

**Comment by uberchilly** [comment]
Any news? Or a temporary workaround?

**Comment by akexorcist** [comment]
@sevenreup Activity recreation is require to apply the language changing. From my little experiment with Android Hilt. Everything work fine. (See Commit https://github.com/akexorcist/Localization/commit/56a92b6bc8a2a34183228d2d7e5ad44b654b82cd). 

If you still have an issue in your project and seem caused by the library. You can provide more information about how you implement the Android Hilt that I can try in my sample project.

@uberchilly If you have any issue from the library with Android Hilt. Please provide some information about it. 👌
