### ISSUE TITLE
Selected language is ignored after app restart on AppCompat 1.3.0-alpha01

### ISSUE THREAD

**Issue by alashow** [akexorcist/Localization#64]
Bug: App starts with default / phone language A, I change the language to B, force close the app from recent apps, open the app again, app's language is back to A. Language is retained if the app is minimized and restored.

I had this issue for a while in my app, but couldn't figure out why. Today I noticed the same behavior on my other app while I was upgrading dependencies. Confirmed the bug in the sample app by changing AppCompat version to `1.3.0-alpha01`. The bug is not present in both `1.1.0` and `1.2.0-alpha01`.

**Comment by iartyst** [comment]
Same problem with `implementation 'androidx.appcompat:appcompat:1.2.0'`
Works fine with `implementation 'androidx.appcompat:appcompat:1.1.0'`

**Comment by AydroidDev** [comment]
Can anyone bring an up-to-date solution to this as soon as possible? Because actually this is the biggest problem so far. We will be glad if you come up with a solution as soon as possible without giving up current dependencies. I cannot update this way. Please spend half an hour for this and upgrade please !!

**Comment by KORuL** [comment]
Hi! I have same problem

**Comment by 10zgurr** [comment]
hi,
i have the same issue when i upgrade the android appcompat lib to the new release which is now 1.2.0

`implementation 'androidx.appcompat:appcompat:1.2.0'`

I couldn't figure out, so can you help us about it? Thanks.

**Comment by alexeyvasilyev** [comment]
The same issue with 'androidx.appcompat:appcompat:1.2.0' and Android 11.

**Comment by alexfrostdev** [comment]
https://developer.android.com/jetpack/androidx/releases/appcompat

Major changes since 1.1.0:

- Deprecated AppCompatDelegate.attachBaseContext(). If you are calling or overriding this method, use AppCompatDelegate.attachBaseContext2() instead.

so maybe this issue related to this change and lib should move to use AppCompatDelegate.attachBaseContext2()

**Comment by XiXiongMaoXiong** [comment]
All you need is love

**Comment by IamMitsuo** [comment]
Hi.

I tried to solve this issue, please see file changed on PR #66. I have tested on my device (Samsung Galaxy Note 8, Android 9), and it's working fine so far.
