### ISSUE TITLE
Dagger Support for BaseActivity

### ISSUE THREAD

**Issue by arif2k17** [akexorcist/Localization#71]
Hi, Thanks or this great library. However i am trying to use this library but can't decide how to add support with Dagger. Currently my BaseActivity extends DaggerAppCompatActivity. Now how can i use your LocalizationActivity for the BaseActivity?

Thanks.

**Comment by akexorcist** [comment]
Using `LocalizationActivityDelegate` instead of `LocalizationActivity` will help you to extends your `BaseActivity` from `DaggerAppCompatActivity` with localization support from the library

For more information about this, see [LocalizationActivityDelegate](https://github.com/akexorcist/Localization#dont-like-appcompat-try-delegate-way)

**Comment by akexorcist** [comment]
There's no update after my last comment. So I gonna close this issue.

If you still have a problem about this, feel free to re-open
