### ISSUE TITLE
Fonts for different languages

### ISSUE THREAD

**Issue by MohammadRezaei92** [akexorcist/Localization#73]
I use 2 res folders for fonts in my app but, when I change the language, related fonts not applied and an app reboot needed to font applied.

**Comment by akhilakhi84** [comment]
[Try Calligraphy](https://github.com/InflationX/Calligraphy) with this library

and instead of using
`<TextView fontPath="fonts/MyFont.ttf"/>`

define as a style in each language value folder
**ex: values/styles.xml**
`<style name="myTextAppearance parent="TextAppearance.MaterialComponents.Body2">
        <item name="fontPath">fonts/enRegular.ttf</item>
</style>`

**ex: values-ml/styles.xml**
`<style name="myTextAppearance parent="TextAppearance.MaterialComponents.Body2">
        <item name="fontPath">fonts/mlRegular.ttf</item>
</style>`

then set it as **textAppearance**
`<TextView android:txtAppearance="@style/myTextAppearance"/>`

**Comment by akexorcist** [comment]
That's normally Android behavior, not from my library.

Even change the language on pure project without my library. Font doesn't changes also

**Comment by akexorcist** [comment]
I close this issue because there's no response for a month. Feel free to re-open this issue when you still have the problem about this.
