### ISSUE TITLE
Black screen appear While change language

### ISSUE THREAD

**Issue by Joseph-TSS** [akexorcist/Localization#78]

**Comment by akexorcist** [comment]
Black screen will appear if your activity took a lot of time to recreate or running in low-spec device. I prefer you to add the blank activity before the activity recreate and dismiss in a few seconds (with fade in/out transition).

I used to added this function to the library. But removed it later because not all developers happy in this behavior.

If you want to add this function by yourself, you can check my removed code from this commit [93f13082](https://github.com/akexorcist/Localization/commit/93f13082e45290844442f6326cb8afade8582193)

**Comment by Joseph-TSS** [comment]
@akexorcist thanks man appreciate that.
